#!/usr/bin/env bash

# Pull from ptrkbrgmn
# git pull ptrkbrgmn master

# git config --global credential.helper /usr/libexec/git-core/git-credential-libsecret

# origin	https://karlpatrikbergman@github.com/karlpatrikbergman/scala-learning.git (fetch)
# origin	https://karlpatrikbergman@github.com/karlpatrikbergman/scala-learning.git (push)
# ptrkbrgmn	https://ptrkbrgmn@github.com/ptrkbrgmn/scala-learning.git (fetch)
# ptrkbrgmn	https://ptrkbrgmn@github.com/ptrkbrgmn/scala-learning.git (push)

push_ptrkbrgmn() {
  #https://ptrkbrgmn@github.com/ptrkbrgmn/scala-learning.git"
  git push -u ptrkbrgmn --all
  git push ptrkbrgmn --tags
}

push_karlpatrikbergman() {
  #https://karlpatrikbergman@github.com/karlpatrikbergman/scala-learning.git
  git push -u origin --all
  git push origin --tags
}

push_ptrkbrgmn
push_karlpatrikbergman
